[colors]
# True black background
primary.background = "0x000000"
primary.foreground = "0x7a828e"

# Cursor color
cursor.text = "0x7a828e"
cursor.cursor = "0xffffff"

# True colors
normal.black = "0x000000"
normal.red = "0xb30000"
normal.green = "0x26cd4d"
normal.yellow = "0xf0b72f"
normal.blue = "0x71b7ff"
normal.magenta = "0xcb9eff"
normal.cyan = "0x39c5cf"
normal.white = "0xd9dee3"

bright.black = "0x9ea7b3"
bright.red = "0xb30000"
bright.green = "0x4ae168"
bright.yellow = "0xf7c843"
bright.blue = "0x91cbff"
bright.magenta = "0xcb9eff"
bright.cyan = "0x39c5cf"
bright.white = "0xd9dee3"
