preload = ~/Pictures/Wallpapers/mima.png

wallpaper {
    monitor = eDP-1
    path = ~/Pictures/Wallpapers/mima.png
    fit_mode = cover
}

wallpaper {
    monitor = DP-1
    path = ~/Pictures/Wallpapers/mima.png
    fit_mode = cover
}
